export const SET_REMAINING_TIME = `SET_REMAINING_TIME`;
export const CLEAR_REMAINING_TIME = `CLEAR_REMAINING_TIME`;
export const UPDATE_REMAINING_TIME = `UPDATE_REMAINING_TIME`;

export const REMAINING_ACTIONS = new Set([
  SET_REMAINING_TIME,
  CLEAR_REMAINING_TIME,
  UPDATE_REMAINING_TIME,
]);
